- name: Get device uptime
  hosts: 
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get uptime using galaxy module
      juniper_junos_command:
        commands:
          - show system uptime

    - name: display uptimes
      debug:
        var: uptime